jobs:
  - job: Windows
    strategy:
      matrix:
        MSVC_2015:
          MUMBLE_QT: qt5
          MUMBLE_HOST: x86_64-pc-windows-msvc
        MSVC_2015_NO_PCH:
          MUMBLE_QT: qt5
          MUMBLE_HOST: x86_64-pc-windows-msvc
          MUMBLE_NO_PCH: 1
    steps:
    - script: git submodule --quiet update --init --recursive
      displayName: 'Fetch submodules'
    - powershell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        choco install 7zip.install -y
      displayName: 'Install 7-Zip via Chocolatey'
    - script: git clone https://github.com/mumble-voip/mumble-releng
      displayName: 'Clone build environment'
    - script: cd mumble-releng/buildenv/1.3.x/win32-static && setup.cmd
      displayName: 'Setup build environment'
    - bash: cd mumble-releng/buildenv/1.3.x/win32-static && ./build-all.bash
      displayName: 'Build all build environment'
    - powershell: scripts/azure-pipelines/build.ps1
      displayName: 'Build'
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Agent.BuildDirectory)
        TargetFolder: $(Build.ArtifactStagingDirectory)
        Contents: '*'
